steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.migrate', '-t', 'us-central1-docker.pkg.dev/proposal-487522/proposalos-prod-containers/db-migrate:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/proposal-487522/proposalos-prod-containers/db-migrate:latest'
