/**
 * Outcome-Based Pricing
 *
 * Tracks revenue generated by clients attributable to recommendations,
 * calculates the platform's configurable revenue share, and generates
 * invoices with full line-item attribution detail.
 *
 * Requirements: 19.1, 19.6
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface OutcomeRevenueEvent {
  id: string;
  clientId: string;
  /** Optional link to the specific recommendation that drove this revenue */
  recommendationId?: string;
  revenueGenerated: number; // in cents
  recordedAt: Date;
}

export interface OutcomeShare {
  clientId: string;
  period: OutcomePeriod;
  totalRevenue: number;       // sum of all events in period (cents)
  sharePercent: number;       // e.g. 10 for 10%
  shareAmount: number;        // totalRevenue * sharePercent / 100 (cents)
  eventCount: number;
}

export interface OutcomeLineItem {
  eventId: string;
  recommendationId?: string;
  revenueGenerated: number;   // cents
  shareAmount: number;        // cents
  recordedAt: Date;
}

export interface OutcomeInvoice {
  id: string;
  clientId: string;
  period: OutcomePeriod;
  lineItems: OutcomeLineItem[];
  totalRevenue: number;       // cents
  totalShareAmount: number;   // cents
  sharePercent: number;
  generatedAt: Date;
  status: 'draft' | 'sent' | 'paid';
}

export interface OutcomePeriod {
  start: Date;
  end: Date;
}

// ─── Configuration ────────────────────────────────────────────────────────────

export interface OutcomePricingConfig {
  /** Revenue share percentage taken by the platform. Default: 10 */
  sharePercent: number;
}

const DEFAULT_CONFIG: OutcomePricingConfig = {
  sharePercent: 10,
};

// ─── In-Memory Store ──────────────────────────────────────────────────────────

/** Keyed by clientId → list of revenue events */
const revenueStore = new Map<string, OutcomeRevenueEvent[]>();

let invoiceCounter = 0;

function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
}

// ─── Core Functions ───────────────────────────────────────────────────────────

/**
 * Record a revenue event for a client, optionally attributed to a specific
 * recommendation.
 *
 * @param clientId         The client that generated the revenue
 * @param revenueGenerated Revenue amount in cents
 * @param recommendationId Optional recommendation that drove this revenue
 * @returns The recorded OutcomeRevenueEvent
 */
export function trackOutcomeRevenue(
  clientId: string,
  revenueGenerated: number,
  recommendationId?: string,
): OutcomeRevenueEvent {
  if (!clientId) throw new Error('clientId is required');
  if (revenueGenerated < 0) throw new Error('revenueGenerated must be non-negative');

  const event: OutcomeRevenueEvent = {
    id: generateId('rev'),
    clientId,
    recommendationId,
    revenueGenerated,
    recordedAt: new Date(),
  };

  const existing = revenueStore.get(clientId) ?? [];
  existing.push(event);
  revenueStore.set(clientId, existing);

  return event;
}

/**
 * Calculate the platform's revenue share for a client over a given period.
 *
 * @param clientId The client to calculate share for
 * @param period   The billing period (start/end dates, inclusive)
 * @param config   Optional config override (e.g. custom sharePercent)
 * @returns OutcomeShare with totals and share amount
 */
export function calculateOutcomeShare(
  clientId: string,
  period: OutcomePeriod,
  config: OutcomePricingConfig = DEFAULT_CONFIG,
): OutcomeShare {
  const events = getEventsInPeriod(clientId, period);

  const totalRevenue = events.reduce((sum, e) => sum + e.revenueGenerated, 0);
  const shareAmount = Math.round((totalRevenue * config.sharePercent) / 100);

  return {
    clientId,
    period,
    totalRevenue,
    sharePercent: config.sharePercent,
    shareAmount,
    eventCount: events.length,
  };
}

/**
 * Generate an invoice for a client's outcome-based billing period.
 * Each line item shows the individual revenue event and the share amount
 * attributed to it, providing full audit trail.
 *
 * @param clientId The client to invoice
 * @param period   The billing period
 * @param config   Optional config override
 * @returns OutcomeInvoice with per-event line items
 */
export function generateOutcomeInvoice(
  clientId: string,
  period: OutcomePeriod,
  config: OutcomePricingConfig = DEFAULT_CONFIG,
): OutcomeInvoice {
  const events = getEventsInPeriod(clientId, period);

  const lineItems: OutcomeLineItem[] = events.map((event) => ({
    eventId: event.id,
    recommendationId: event.recommendationId,
    revenueGenerated: event.revenueGenerated,
    shareAmount: Math.round((event.revenueGenerated * config.sharePercent) / 100),
    recordedAt: event.recordedAt,
  }));

  const totalRevenue = lineItems.reduce((sum, li) => sum + li.revenueGenerated, 0);
  const totalShareAmount = lineItems.reduce((sum, li) => sum + li.shareAmount, 0);

  invoiceCounter += 1;

  return {
    id: `inv_outcome_${invoiceCounter}_${generateId('i')}`,
    clientId,
    period,
    lineItems,
    totalRevenue,
    totalShareAmount,
    sharePercent: config.sharePercent,
    generatedAt: new Date(),
    status: 'draft',
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getEventsInPeriod(clientId: string, period: OutcomePeriod): OutcomeRevenueEvent[] {
  const events = revenueStore.get(clientId) ?? [];
  return events.filter(
    (e) => e.recordedAt >= period.start && e.recordedAt <= period.end,
  );
}

/**
 * Retrieve all revenue events for a client (useful for testing / auditing).
 */
export function getRevenueEvents(clientId: string): OutcomeRevenueEvent[] {
  return [...(revenueStore.get(clientId) ?? [])];
}

/**
 * Clear all stored revenue events (intended for test isolation only).
 */
export function _clearStore(): void {
  revenueStore.clear();
  invoiceCounter = 0;
}
