import { FindingType, Finding as PrismaFinding } from '@prisma/client';
import { z } from 'zod';

import { PainCluster } from '../diagnosis/types';

// Runtime Finding type - extends Prisma Finding with relaxed types for runtime flexibility
// The metrics field uses Record<string, unknown> instead of JsonValue for easier runtime access
export type FindingRuntime = {
  // Core fields from Prisma Finding
  id: string;
  auditId: string;
  module: string;
  category: string;
  type: FindingType;
  title: string;
  description: string | null;
  evidence: unknown;
  // Relaxed metrics type for runtime flexibility
  metrics: Record<string, unknown>;
  impactScore: number;
  confidenceScore: number;
  effortEstimate: string | null;
  recommendedFix: unknown;
  manuallyEdited: boolean;
  excluded: boolean;
  confidenceLevel: string | null;
  createdAt: Date;
  tenantId: string;
};

// Tier configuration schema
export const TierConfigSchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().optional(),
  findingIds: z.array(z.string()),
  deliveryTime: z.string().optional(),
  price: z.number().optional(),
  recommended: z.boolean().optional(),
  features: z.array(z.string()).optional(),
  badge: z.string().optional(),
  roi: z
    .object({
      monthlyValue: z.number(),
      ratio: z.number(),
      scenarios: z
        .object({
          best: z.number(),
          base: z.number(),
          worst: z.number(),
          assumptions: z.array(z.string()),
        })
        .optional(),
    })
    .optional(),
  visualEvidence: z
    .array(
      z.object({
        screenshotUrl: z.string().url(),
        annotationText: z.string(),
        findingRef: z.string(),
        severity: z.number(),
      })
    )
    .optional(),
});

// Pricing schema
export const PricingSchema = z.object({
  essentials: z.number().min(0),
  growth: z.number().min(0),
  premium: z.number().min(0),
  currency: z.string().default('USD'),
});

// Comparison report schemas
export const ComparisonTableRowSchema = z.object({
  metric: z.string(),
  prospectValue: z.union([z.string(), z.number()]),
  prospectStatus: z.enum(['win', 'lose', 'tie']),
  competitorValues: z.array(
    z.object({
      name: z.string(),
      value: z.union([z.string(), z.number()]),
      status: z.enum(['win', 'lose', 'tie']),
    })
  ),
});

export const ComparisonReportSchema = z
  .object({
    prospect: z.object({
      name: z.string(),
      performanceScore: z.number().optional(),
      seoScore: z.number().optional(),
      accessibilityScore: z.number().optional(),
      mobileScore: z.number().optional(),
      loadTimeSeconds: z.number().optional(),
      rating: z.number().optional(),
      reviewCount: z.number().optional(),
    }),
    competitors: z.array(
      z.object({
        name: z.string(),
        performanceScore: z.number().optional(),
        seoScore: z.number().optional(),
        accessibilityScore: z.number().optional(),
        mobileScore: z.number().optional(),
        loadTimeSeconds: z.number().optional(),
        rating: z.number().optional(),
        reviewCount: z.number().optional(),
      })
    ),
    prospectRank: z.number(),
    winningCategories: z.array(z.string()),
    losingCategories: z.array(z.string()),
    biggestGap: z
      .object({
        category: z.string(),
        prospectScore: z.number(),
        bestCompetitorScore: z.number(),
        competitorName: z.string(),
        gap: z.number(),
      })
      .nullable()
      .optional(),
    summaryStatement: z.string(),
    positiveStatement: z.string(),
    urgencyStatement: z.string(),
    quickWins: z.array(
      z.object({
        action: z.string(),
        effortEstimate: z.string(),
        expectedImpact: z.string(),
      })
    ),
    comparisonTableRows: z.array(ComparisonTableRowSchema).optional(),
    summaryRow: z.string().optional(),
    whereAhead: z.array(z.string()).optional(),
    whereBehind: z.array(z.string()).optional(),
  })
  .nullable()
  .optional();

// Top actions schema
export const TopActionSchema = z
  .object({
    findingId: z.string(),
    title: z.string(),
    impact: z.number(),
    effort: z.string(),
    timeline: z.string(),
  })
  .array()
  .optional();

// AI Disclaimer - Required for all proposals
export const AIDisclaimerSchema = z.object({
  disclaimer: z
    .string()
    .refine(
      (val) => val.includes('AI') || val.includes('artificial intelligence'),
      'Disclaimer must mention AI-generated content'
    ),
  verificationRequired: z.boolean().default(true),
});

// Main proposal result schema
export const ProposalResultSchema = z.object({
  executiveSummary: z.string().min(50).max(500),
  aiDisclaimer: AIDisclaimerSchema.default({
    disclaimer: 'Generated by AI. Verify recommendations with a qualified professional.',
    verificationRequired: true,
  }),
  painClusters: z.array(
    z.object({
      rootCause: z.string(),
      severity: z.enum(['critical', 'high', 'medium', 'low']),
      narrative: z.string().optional(),
      findingIds: z.array(z.string()),
      impactScore: z.number().optional(),
    })
  ),
  comparisonReport: ComparisonReportSchema.optional(),
  topActions: TopActionSchema,
  tiers: z.object({
    essentials: TierConfigSchema,
    growth: TierConfigSchema,
    premium: TierConfigSchema,
  }),
  pricing: PricingSchema,
  assumptions: z.array(z.string()).min(1),
  disclaimers: z.array(z.string()).min(1),
  nextSteps: z.array(z.string()).min(1),
});

// Validation result schema
export const ValidationResultSchema = z.object({
  valid: z.boolean(),
  errors: z.array(z.string()),
  warnings: z.array(z.string()).optional(),
});

// Citation validation schema
export const CitationValidationSchema = z.object({
  valid: z.boolean(),
  errors: z.array(z.string()),
  missingCitations: z.array(z.string()),
  orphanedCitations: z.array(z.string()),
});

// Hallucination detection schema
export const HallucinationDetectionSchema = z.object({
  hasHallucinations: z.boolean(),
  flaggedClaims: z.array(
    z.object({
      claim: z.string(),
      location: z.string(),
      reason: z.string(),
      severity: z.enum(['low', 'medium', 'high']),
    })
  ),
  confidenceScore: z.number().min(0).max(1),
});

// Complete validation output schema
export const ValidationOutputSchema = z.object({
  overallValid: z.boolean(),
  proposalValidation: ValidationResultSchema,
  citationValidation: CitationValidationSchema,
  hallucinationDetection: HallucinationDetectionSchema,
  qualityScore: z.number().min(0).max(1),
});

export type ProposalResult = z.infer<typeof ProposalResultSchema>;
export type TierConfig = z.infer<typeof TierConfigSchema>;
export type ProposalPricing = z.infer<typeof PricingSchema>;
export type ComparisonReport = z.infer<typeof ComparisonReportSchema>;
export type ValidationResult = z.infer<typeof ValidationResultSchema>;
export type CitationValidation = z.infer<typeof CitationValidationSchema>;
export type HallucinationDetection = z.infer<typeof HallucinationDetectionSchema>;
export type ValidationOutput = z.infer<typeof ValidationOutputSchema>;

/**
 * Validate complete proposal structure
 */
export function validateProposalStructure(proposal: unknown): ValidationResult {
  try {
    ProposalResultSchema.parse(proposal);
    return {
      valid: true,
      errors: [],
      warnings: [],
    };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        valid: false,
        errors: error.errors.map((e) => `${e.path.join('.')}: ${e.message}`),
        warnings: [],
      };
    }
    return {
      valid: false,
      errors: ['Invalid proposal structure'],
      warnings: [],
    };
  }
}

/**
 * Validate citations in proposal against findings
 */
export function validateCitations(
  proposal: ProposalResult,
  findings: FindingRuntime[]
): CitationValidation {
  const errors: string[] = [];
  const missingCitations: string[] = [];
  const orphanedCitations: string[] = [];

  const findingIds = new Set(findings.map((f) => f.id));

  // Check tier citations
  for (const [tierName, tier] of Object.entries(proposal.tiers)) {
    for (const id of tier.findingIds) {
      if (!findingIds.has(id)) {
        missingCitations.push(`${tierName} tier references non-existent finding: ${id}`);
      }
    }
  }

  // Check pain clusters
  for (const cluster of proposal.painClusters) {
    for (const id of cluster.findingIds) {
      if (!findingIds.has(id)) {
        missingCitations.push(
          `Cluster "${cluster.rootCause}" references non-existent finding: ${id}`
        );
      }
    }
  }

  // Find orphaned findings (findings not referenced anywhere)
  const referencedIds = new Set<string>();
  Object.values(proposal.tiers).forEach((tier) => {
    tier.findingIds.forEach((id: string) => referencedIds.add(id));
  });
  proposal.painClusters.forEach((cluster) => {
    cluster.findingIds.forEach((id: string) => referencedIds.add(id));
  });

  findings.forEach((f) => {
    if (!referencedIds.has(f.id)) {
      orphanedCitations.push(`Finding "${f.title}" is not referenced in proposal`);
    }
  });

  return {
    valid: missingCitations.length === 0,
    errors: [...missingCitations, ...orphanedCitations],
    missingCitations,
    orphanedCitations,
  };
}

/**
 * Detect hallucinations in proposal content
 * P1-1 FIX: Enhanced with semantic similarity and numeric claim verification
 */
export function detectHallucinations(
  proposal: ProposalResult,
  findings: FindingRuntime[]
): HallucinationDetection {
  const flaggedClaims: Array<{
    claim: string;
    location: string;
    reason: string;
    severity: 'low' | 'medium' | 'high';
  }> = [];
  let totalClaims = 0;
  let supportedClaims = 0;

  // Build comprehensive finding reference data
  const findingRefs = findings.map((f) => ({
    id: f.id,
    title: (f.title || '').toLowerCase(),
    description: (f.description || '').toLowerCase(),
    metrics: f.metrics || {},
    impactScore: f.impactScore || 0,
    effortEstimate: f.effortEstimate || 'MEDIUM',
  }));

  // Check executive summary for supported claims
  const summary = proposal.executiveSummary;
  const summaryLower = summary.toLowerCase();

  // P1-1 FIX: Enhanced keyword matching with phrase extraction
  const keyPhrases = extractKeyPhrases(summary);

  for (const phrase of keyPhrases) {
    totalClaims++;
    let foundSupport = false;

    for (const finding of findingRefs) {
      // Check if phrase appears in finding title or description
      if (finding.title.includes(phrase) || finding.description.includes(phrase)) {
        foundSupport = true;
        supportedClaims++;
        break;
      }

      // Check for semantic similarity (simple word overlap)
      const phraseWords = phrase.split(/\s+/).filter((w) => w.length > 3);
      const findingWords = `${finding.title} ${finding.description}`.split(/\s+/);
      const overlap = phraseWords.filter((w) => findingWords.includes(w)).length;

      if (phraseWords.length > 0 && overlap / phraseWords.length >= 0.5) {
        foundSupport = true;
        supportedClaims++;
        break;
      }
    }

    if (!foundSupport && phrase.length > 5) {
      // Check if it's a generic statement (acceptable without specific finding)
      const genericPhrases = [
        'our team',
        'we will',
        'our analysis',
        'this proposal',
        'your business',
        'online presence',
      ];
      const isGeneric = genericPhrases.some((gp) => phrase.includes(gp));

      if (!isGeneric) {
        flaggedClaims.push({
          claim: `Phrase "${phrase.substring(0, 50)}${phrase.length > 50 ? '...' : ''}" lacks clear finding support`,
          location: 'executiveSummary',
          reason: 'Claim may not be grounded in audit findings',
          severity: 'medium',
        });
      } else {
        // Generic phrases count as supported
        supportedClaims++;
      }
    }
  }

  // P1-1 FIX: Enhanced numeric claim verification
  const numericClaims = extractNumericClaims(summary);

  for (const claim of numericClaims) {
    totalClaims++;
    let foundSupport = false;

    // Check if number appears in any finding metrics
    for (const finding of findingRefs) {
      const metricsValues = Object.values(finding.metrics).filter(
        (v) => typeof v === 'number'
      ) as number[];

      // Allow 10% tolerance for rounded numbers
      for (const metricValue of metricsValues) {
        if (Math.abs(metricValue - claim.value) / Math.max(metricValue, 1) <= 0.1) {
          foundSupport = true;
          supportedClaims++;
          break;
        }
      }

      // Check impact score matches
      if (claim.value === finding.impactScore || claim.value === Math.round(finding.impactScore)) {
        foundSupport = true;
        supportedClaims++;
        break;
      }
    }

    if (!foundSupport) {
      flaggedClaims.push({
        claim: `Numeric claim "${claim.value}${claim.unit || ''}" lacks supporting evidence in findings`,
        location: 'executiveSummary',
        reason: 'Potential fabricated statistic',
        severity: 'high',
      });
    }
  }

  // Check tier descriptions for unsubstantiated claims
  for (const [tierName, tier] of Object.entries(proposal.tiers)) {
    const tierText = `${tier.name} ${tier.description}`.toLowerCase();

    // Check for guarantee language
    const guaranteePatterns = [
      /\bguaranteed?\b/gi,
      /\bwill\s+(100%|definitely|certainly)\b/gi,
      /\brisk[- ]?free\b/gi,
    ];

    for (const pattern of guaranteePatterns) {
      if (pattern.test(tierText)) {
        flaggedClaims.push({
          claim: `Tier ${tierName} contains potential guarantee language`,
          location: `tiers.${tierName}`,
          reason: 'Guarantees may create legal liability',
          severity: 'high',
        });
      }
    }
  }

  const confidenceScore =
    totalClaims > 0 ? Math.max(0, Math.min(1, supportedClaims / totalClaims)) : 1;

  return {
    hasHallucinations: flaggedClaims.length > 0,
    flaggedClaims,
    confidenceScore,
  };
}

/**
 * Extract key phrases from text for claim verification
 */
function extractKeyPhrases(text: string): string[] {
  // Remove common stop words and extract meaningful phrases
  const stopWords = new Set([
    'the',
    'a',
    'an',
    'is',
    'are',
    'was',
    'were',
    'be',
    'been',
    'being',
    'have',
    'has',
    'had',
    'do',
    'does',
    'did',
    'will',
    'would',
    'could',
    'should',
    'may',
    'might',
    'must',
    'shall',
    'can',
    'need',
    'dare',
    'ought',
    'used',
    'to',
    'of',
    'in',
    'for',
    'on',
    'with',
    'at',
    'by',
    'from',
    'as',
    'into',
    'through',
    'during',
    'before',
    'after',
    'above',
    'below',
    'between',
    'under',
    'again',
    'further',
    'then',
    'once',
    'here',
    'there',
    'when',
    'where',
    'why',
    'how',
    'all',
    'each',
    'few',
    'more',
    'most',
    'other',
    'some',
    'such',
    'no',
    'nor',
    'not',
    'only',
    'own',
    'same',
    'so',
    'than',
    'too',
    'very',
    'just',
    'and',
    'but',
    'if',
    'or',
    'because',
    'until',
    'while',
    'although',
    'though',
    'after',
    'before',
    'when',
    'whenever',
    'where',
    'wherever',
    'whether',
    'which',
    'while',
    'who',
    'whoever',
    'whom',
    'whose',
    'what',
    'whatever',
  ]);

  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const phrases: string[] = [];

  for (const sentence of sentences) {
    const words = sentence
      .split(/\s+/)
      .filter((w) => !stopWords.has(w.toLowerCase()) && w.length > 2);

    // Extract 2-3 word phrases
    for (let i = 0; i < words.length - 1; i++) {
      const phrase = `${words[i]} ${words[i + 1]}`.toLowerCase();
      if (phrase.length > 5) {
        phrases.push(phrase);
      }
      if (i < words.length - 2) {
        const longerPhrase = `${words[i]} ${words[i + 1]} ${words[i + 2]}`.toLowerCase();
        if (longerPhrase.length > 8) {
          phrases.push(longerPhrase);
        }
      }
    }
  }

  return [...new Set(phrases)]; // Deduplicate
}

/**
 * Extract numeric claims from text
 */
function extractNumericClaims(
  text: string
): Array<{ value: number; unit?: string; context: string }> {
  const claims: Array<{ value: number; unit?: string; context: string }> = [];

  // Match percentages
  const percentMatches = text.match(/(\d+(?:\.\d+)?)\s*%/g);
  if (percentMatches) {
    for (const match of percentMatches) {
      const value = parseFloat(match);
      // Flag unusually high percentages as potential hallucinations
      if (value > 100 || (value > 50 && !text.toLowerCase().includes('up to'))) {
        claims.push({ value, unit: '%', context: match });
      }
    }
  }

  // Match dollar amounts
  const dollarMatches = text.match(/\$(\d+(?:,\d{3})*(?:\.\d{2})?)/g);
  if (dollarMatches) {
    for (const match of dollarMatches) {
      const value = parseFloat(match.replace(/[$,]/g, ''));
      claims.push({ value, unit: '$', context: match });
    }
  }

  // Match time claims
  const timeMatches = text.match(/(\d+(?:\.\d+)?)\s*(days?|weeks?|months?|hours?)/gi);
  if (timeMatches) {
    for (const match of timeMatches) {
      const value = parseFloat(match);
      claims.push({ value, context: match });
    }
  }

  return claims;
}

/**
 * Complete validation pipeline
 */
export function validateCompleteProposal(
  proposal: ProposalResult,
  findings: FindingRuntime[]
): ValidationOutput {
  const proposalValidation = validateProposalStructure(proposal);
  const citationValidation = validateCitations(proposal, findings);
  const hallucinationDetection = detectHallucinations(proposal, findings);

  const overallValid =
    proposalValidation.valid &&
    citationValidation.valid &&
    !hallucinationDetection.hasHallucinations;
  const qualityScore = hallucinationDetection.confidenceScore;

  return {
    overallValid,
    proposalValidation,
    citationValidation,
    hallucinationDetection,
    qualityScore,
  };
}
