/**
 * lib/resilience/providerPolicy.ts
 *
 * Resilience policies per third-party provider.
 */

import { ProviderName, ProviderPolicy } from './types';

export const PROVIDER_POLICIES: Record<ProviderName, ProviderPolicy> = {
  pagespeed: {
    timeoutMs: 30000,
    maxAttempts: 2,
    baseDelayMs: 500,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 30,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  'google-places': {
    timeoutMs: 15000,
    maxAttempts: 3,
    baseDelayMs: 500,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 120,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  serpapi: {
    timeoutMs: 20000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 60,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  yelp: {
    timeoutMs: 15000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 30,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  gemini: {
    timeoutMs: 30000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
      'overloaded',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 60,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  vertex: {
    timeoutMs: 30000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
      'overloaded',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 60,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  resend: {
    timeoutMs: 30000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 60,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: false,
  },
  stripe: {
    timeoutMs: 30000,
    maxAttempts: 3,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 100,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: false,
  },
  crawler: {
    timeoutMs: 45000,
    maxAttempts: 1,
    baseDelayMs: 500,
    maxDelayMs: 5000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: ['timeout', 'econnreset', 'etimedout', 'enotfound', 'econnrefused'],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 30,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
  generic: {
    timeoutMs: 15000,
    maxAttempts: 2,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    jitter: true,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    retryableErrorKinds: [
      'timeout',
      'econnreset',
      'etimedout',
      'enotfound',
      'econnrefused',
      'rate limit',
    ],
    rateLimitWindowMs: 60000,
    rateLimitMaxCalls: 60,
    circuitBreakerFailureThreshold: 5,
    circuitBreakerCooldownMs: 60000,
    tenantScopingRequired: false,
    degradationAllowed: true,
  },
};

export function getProviderPolicy(provider: ProviderName): ProviderPolicy {
  return PROVIDER_POLICIES[provider] || PROVIDER_POLICIES.generic;
}
